# ~/.config/starship.toml

# Global Configuration
format = "in [$directory](bold #d8a657)\n$git_branch [>](bold #d8a657) "

add_newline = true

# Time
[time]
format = "[󱑃 $time]($style)"
style = "bold #d8a657"  # Gruvbox neutral yellow
use_12hr = true
disabled = false

# Directory Module
[directory]
style = "bold #d8a657"  # Gruvbox bright yellow (accent)
format = "$path"
read_only = " "
truncate_to_repo = true
disabled = false

# Git Module
[git_branch]
symbol = "  "
format = "[$symbol$branch]($style)"
style = "bold #d8a657"
disabled = false

# Sudo
[sudo]
style = "bold #d8a657"  # Gruvbox red for root privilege
disabled = false

# Username
[username]
style_root = "bold #fb4934"  # Gruvbox bright red
style_user = "bold #83a598"  # Gruvbox bright blue
format = "[$user]($style)"
show_always = true

