# ~/.config/starship.toml

# Global Configuration
format = "in [$directory](bold #b7bdf8)\n$git_branch [>](bold #b7bdf8) "

add_newline = true

# Time
[time]
format = "[󱑃 $time]($style)"
style = "bold #a6e3a1"
use_12hr = true
disabled = false

# Directory Module
[directory]
style = "bold #b7bdf8"
format = "$path"
read_only = " "
truncate_to_repo = true
disabled = false

# Git Module
[git_branch]
symbol = "  "
format = "[$symbol$branch]($style)"
style = "bold #b7bdf8"
disabled = false

# Sudo
[sudo]
style = "bold #b7bdf8"
disabled = false

# Username
[username]
style_root = "bold #b7bdf8"
style_user = "bold #b7bdf8"
format = "[$user]($style)"
show_always = true
